import { getDb } from './server/db';
import { icpAssessmentSections, icpAssessmentQuestions } from './drizzle/schema';

async function seedICPAssessment() {
  console.log('🌱 Seeding ICP & Sales Enablement Assessment...');

  // Create sections
  const sections = [
    {
      name: 'ICP Discovery',
      description: 'Understand your ideal customer profile, target markets, and customer buying behaviors',
      order: 1,
    },
    {
      name: 'Sales Methodology Maturity',
      description: 'Assess your current sales process, methodology adoption, and team performance',
      order: 2,
    },
    {
      name: 'Sales Enablement Maturity',
      description: 'Evaluate your sales enablement resources, training, technology, and coaching effectiveness',
      order: 3,
    },
  ];

  const db = await getDb();
  if (!db) {
    console.error('❌ Database not available');
    process.exit(1);
  }

  for (const section of sections) {
    await db.insert(icpAssessmentSections).values(section);
  }

  console.log('✅ Sections created');

  // ICP Discovery Questions
  const icpQuestions = [
    // Business Model & Revenue Streams
    {
      sectionId: 1,
      category: 'Business Model',
      question: 'What is your primary business model?',
      questionType: 'select',
      options: JSON.stringify(['B2B', 'B2C', 'B2B2C', 'Marketplace', 'SaaS', 'Services', 'Product + Services', 'Other']),
      helpText: 'Select the model that best describes how you generate revenue',
      required: true,
      order: 1,
    },
    {
      sectionId: 1,
      category: 'Business Model',
      question: 'What are your primary revenue streams?',
      questionType: 'multiselect',
      options: JSON.stringify(['One-time sales', 'Recurring subscriptions', 'Usage-based pricing', 'Professional services', 'Licensing', 'Advertising', 'Marketplace fees', 'Other']),
      helpText: 'Select all that apply',
      required: true,
      order: 2,
    },
    {
      sectionId: 1,
      category: 'Business Model',
      question: 'What is your average deal size or transaction value?',
      questionType: 'select',
      options: JSON.stringify(['Under $1K', '$1K - $10K', '$10K - $50K', '$50K - $100K', '$100K - $500K', '$500K - $1M', 'Over $1M']),
      helpText: 'This helps determine the appropriate sales methodology',
      required: true,
      order: 3,
    },
    {
      sectionId: 1,
      category: 'Business Model',
      question: 'What is your typical sales cycle length?',
      questionType: 'select',
      options: JSON.stringify(['Less than 1 week', '1-4 weeks', '1-3 months', '3-6 months', '6-12 months', 'Over 12 months']),
      helpText: 'From first contact to closed deal',
      required: true,
      order: 4,
    },

    // Target Markets & Verticals
    {
      sectionId: 1,
      category: 'Target Markets',
      question: 'What industries or verticals do you primarily serve?',
      questionType: 'textarea',
      options: null,
      helpText: 'List the top 3-5 industries where you have the most success',
      required: true,
      order: 5,
    },
    {
      sectionId: 1,
      category: 'Target Markets',
      question: 'Do you serve multiple distinct customer segments or verticals?',
      questionType: 'boolean',
      options: JSON.stringify(['Yes', 'No']),
      helpText: 'This will help us create multiple ICPs if needed',
      required: true,
      order: 6,
    },
    {
      sectionId: 1,
      category: 'Target Markets',
      question: 'What is the typical company size of your ideal customer?',
      questionType: 'select',
      options: JSON.stringify(['1-10 employees', '11-50 employees', '51-200 employees', '201-500 employees', '501-1000 employees', '1000-5000 employees', '5000+ employees']),
      helpText: 'Select the range that represents your sweet spot',
      required: true,
      order: 7,
    },
    {
      sectionId: 1,
      category: 'Target Markets',
      question: 'What is the typical revenue range of your ideal customer?',
      questionType: 'select',
      options: JSON.stringify(['Under $1M', '$1M - $10M', '$10M - $50M', '$50M - $100M', '$100M - $500M', '$500M - $1B', 'Over $1B']),
      helpText: 'This helps identify the right decision-makers and buying process',
      required: true,
      order: 8,
    },
    {
      sectionId: 1,
      category: 'Target Markets',
      question: 'What geographic markets do you serve?',
      questionType: 'multiselect',
      options: JSON.stringify(['North America', 'Latin America', 'Europe', 'Asia Pacific', 'Middle East', 'Africa', 'Global']),
      helpText: 'Select all regions where you actively sell',
      required: true,
      order: 9,
    },

    // Customer Pain Points
    {
      sectionId: 1,
      category: 'Customer Pain Points',
      question: 'What are the top 3 pain points your solution addresses?',
      questionType: 'textarea',
      options: null,
      helpText: 'Be specific about the business problems you solve',
      required: true,
      order: 10,
    },
    {
      sectionId: 1,
      category: 'Customer Pain Points',
      question: 'How do customers typically discover they have these pain points?',
      questionType: 'textarea',
      options: null,
      helpText: 'What triggers awareness of the problem?',
      required: true,
      order: 11,
    },
    {
      sectionId: 1,
      category: 'Customer Pain Points',
      question: 'What is the cost of inaction for your customers?',
      questionType: 'textarea',
      options: null,
      helpText: 'What happens if they don\'t solve this problem?',
      required: true,
      order: 12,
    },
    {
      sectionId: 1,
      category: 'Customer Pain Points',
      question: 'What alternatives or workarounds do customers use before buying from you?',
      questionType: 'textarea',
      options: null,
      helpText: 'Manual processes, spreadsheets, competitors, etc.',
      required: true,
      order: 13,
    },

    // Buying Behaviors
    {
      sectionId: 1,
      category: 'Buying Behaviors',
      question: 'Who is typically the economic buyer (budget holder) in your deals?',
      questionType: 'multiselect',
      options: JSON.stringify(['CEO/Owner', 'CFO', 'CRO/VP Sales', 'CMO/VP Marketing', 'CTO/VP Engineering', 'COO', 'Department Head', 'Other']),
      helpText: 'Select all that apply',
      required: true,
      order: 14,
    },
    {
      sectionId: 1,
      category: 'Buying Behaviors',
      question: 'Who are the typical influencers or champions in your deals?',
      questionType: 'textarea',
      options: null,
      helpText: 'Roles that advocate for your solution internally',
      required: true,
      order: 15,
    },
    {
      sectionId: 1,
      category: 'Buying Behaviors',
      question: 'How many stakeholders are typically involved in the buying decision?',
      questionType: 'select',
      options: JSON.stringify(['1-2', '3-5', '6-10', '11-15', '15+']),
      helpText: 'This impacts your sales complexity',
      required: true,
      order: 16,
    },
    {
      sectionId: 1,
      category: 'Buying Behaviors',
      question: 'What are the most common objections you hear during the sales process?',
      questionType: 'textarea',
      options: null,
      helpText: 'List the top 3-5 objections',
      required: true,
      order: 17,
    },
    {
      sectionId: 1,
      category: 'Buying Behaviors',
      question: 'What criteria do customers use to evaluate solutions like yours?',
      questionType: 'textarea',
      options: null,
      helpText: 'Features, price, support, implementation time, ROI, etc.',
      required: true,
      order: 18,
    },

    // Current Customer Base
    {
      sectionId: 1,
      category: 'Current Customer Base',
      question: 'Describe your best customers (those with highest LTV, lowest churn, fastest close)',
      questionType: 'textarea',
      options: null,
      helpText: 'What characteristics do they share?',
      required: true,
      order: 19,
    },
    {
      sectionId: 1,
      category: 'Current Customer Base',
      question: 'What percentage of your revenue comes from your top 20% of customers?',
      questionType: 'select',
      options: JSON.stringify(['Less than 20%', '20-40%', '40-60%', '60-80%', 'Over 80%']),
      helpText: 'This reveals customer concentration',
      required: true,
      order: 20,
    },
    {
      sectionId: 1,
      category: 'Current Customer Base',
      question: 'What is your customer acquisition cost (CAC)?',
      questionType: 'select',
      options: JSON.stringify(['Under $100', '$100-$500', '$500-$2K', '$2K-$10K', '$10K-$50K', '$50K+', 'Don\'t know']),
      helpText: 'Total sales & marketing cost divided by new customers',
      required: true,
      order: 21,
    },
    {
      sectionId: 1,
      category: 'Current Customer Base',
      question: 'What is your customer lifetime value (LTV)?',
      questionType: 'select',
      options: JSON.stringify(['Under $1K', '$1K-$10K', '$10K-$50K', '$50K-$100K', '$100K-$500K', '$500K+', 'Don\'t know']),
      helpText: 'Average revenue per customer over their lifetime',
      required: true,
      order: 22,
    },
    {
      sectionId: 1,
      category: 'Current Customer Base',
      question: 'What is your LTV:CAC ratio?',
      questionType: 'select',
      options: JSON.stringify(['Less than 1:1', '1:1 to 2:1', '2:1 to 3:1', '3:1 to 5:1', 'Over 5:1', 'Don\'t know']),
      helpText: 'Healthy SaaS businesses target 3:1 or higher',
      required: true,
      order: 23,
    },

    // Product/Service Positioning
    {
      sectionId: 1,
      category: 'Positioning',
      question: 'What is your unique value proposition?',
      questionType: 'textarea',
      options: null,
      helpText: 'What makes you different from alternatives?',
      required: true,
      order: 24,
    },
    {
      sectionId: 1,
      category: 'Positioning',
      question: 'Who are your top 3 competitors?',
      questionType: 'textarea',
      options: null,
      helpText: 'Direct competitors or alternative solutions',
      required: true,
      order: 25,
    },
    {
      sectionId: 1,
      category: 'Positioning',
      question: 'What are your key differentiators vs. competitors?',
      questionType: 'textarea',
      options: null,
      helpText: 'Why do customers choose you over alternatives?',
      required: true,
      order: 26,
    },
    {
      sectionId: 1,
      category: 'Positioning',
      question: 'How would you categorize your solution?',
      questionType: 'select',
      options: JSON.stringify(['Best-in-class/Point solution', 'Platform/Suite', 'All-in-one', 'Niche specialist', 'Enterprise-grade', 'SMB-focused', 'Other']),
      helpText: 'This affects your positioning strategy',
      required: true,
      order: 27,
    },
  ];

  // Sales Methodology Maturity Questions
  const methodologyQuestions = [
    // Current Sales Process
    {
      sectionId: 2,
      category: 'Sales Process',
      question: 'Do you have a defined, documented sales process?',
      questionType: 'select',
      options: JSON.stringify(['No formal process', 'Informal/undocumented', 'Documented but not followed', 'Documented and mostly followed', 'Documented and strictly followed']),
      helpText: 'Process consistency is key to scalability',
      required: true,
      order: 1,
    },
    {
      sectionId: 2,
      category: 'Sales Process',
      question: 'How many stages are in your sales process?',
      questionType: 'select',
      options: JSON.stringify(['No defined stages', '3-4 stages', '5-6 stages', '7-8 stages', '9+ stages']),
      helpText: 'Typical B2B processes have 5-7 stages',
      required: true,
      order: 2,
    },
    {
      sectionId: 2,
      category: 'Sales Process',
      question: 'Do you have clear exit criteria for each stage of your sales process?',
      questionType: 'select',
      options: JSON.stringify(['No', 'Somewhat - informal guidelines', 'Yes - documented criteria', 'Yes - documented and enforced']),
      helpText: 'Exit criteria prevent deals from stalling',
      required: true,
      order: 3,
    },
    {
      sectionId: 2,
      category: 'Sales Process',
      question: 'What percentage of your sales team consistently follows your sales process?',
      questionType: 'select',
      options: JSON.stringify(['0-25%', '26-50%', '51-75%', '76-90%', '91-100%']),
      helpText: 'Process adherence drives predictability',
      required: true,
      order: 4,
    },

    // Methodology Adoption
    {
      sectionId: 2,
      category: 'Methodology Adoption',
      question: 'Have you adopted a specific sales methodology?',
      questionType: 'select',
      options: JSON.stringify(['No', 'Considering one', 'Recently adopted', 'Adopted 1-2 years ago', 'Adopted 3+ years ago']),
      helpText: 'Methodologies provide repeatable frameworks',
      required: true,
      order: 5,
    },
    {
      sectionId: 2,
      category: 'Methodology Adoption',
      question: 'If yes, which sales methodology have you adopted?',
      questionType: 'select',
      options: JSON.stringify(['None', 'MEDDIC/MEDDPICC', 'Challenger Sale', 'SPIN Selling', 'Sandler', 'Solution Selling', 'Value Selling', 'Gap Selling', 'Account-Based Selling', 'Consultative Selling', 'Other']),
      helpText: 'Select the primary methodology',
      required: false,
      order: 6,
    },
    {
      sectionId: 2,
      category: 'Methodology Adoption',
      question: 'How would you rate your team\'s proficiency with your chosen methodology?',
      questionType: 'rating',
      options: JSON.stringify({ min: 1, max: 10 }),
      helpText: '1 = Just started, 10 = Expert level',
      required: false,
      order: 7,
    },
    {
      sectionId: 2,
      category: 'Methodology Adoption',
      question: 'Do you have a qualification framework (e.g., BANT, MEDDIC, NEAT)?',
      questionType: 'select',
      options: JSON.stringify(['No formal framework', 'Informal criteria', 'BANT', 'MEDDIC/MEDDPICC', 'NEAT', 'Custom framework', 'Other']),
      helpText: 'Qualification prevents wasted time on bad-fit deals',
      required: true,
      order: 8,
    },

    // Sales Team Structure
    {
      sectionId: 2,
      category: 'Sales Team',
      question: 'How many people are on your sales team?',
      questionType: 'select',
      options: JSON.stringify(['Just me', '2-5', '6-10', '11-25', '26-50', '51-100', '100+']),
      helpText: 'Team size impacts methodology complexity',
      required: true,
      order: 9,
    },
    {
      sectionId: 2,
      category: 'Sales Team',
      question: 'Is your sales team specialized by role?',
      questionType: 'multiselect',
      options: JSON.stringify(['No specialization - full-cycle reps', 'SDRs/BDRs (prospecting)', 'AEs (closing)', 'SEs/Solution Consultants', 'Customer Success/Account Management', 'Sales Ops/Rev Ops']),
      helpText: 'Select all that apply',
      required: true,
      order: 10,
    },
    {
      sectionId: 2,
      category: 'Sales Team',
      question: 'What is your sales team\'s average tenure?',
      questionType: 'select',
      options: JSON.stringify(['Less than 6 months', '6-12 months', '1-2 years', '2-3 years', '3-5 years', '5+ years']),
      helpText: 'High turnover indicates enablement or culture issues',
      required: true,
      order: 11,
    },
    {
      sectionId: 2,
      category: 'Sales Team',
      question: 'What percentage of your sales team is hitting quota?',
      questionType: 'select',
      options: JSON.stringify(['0-25%', '26-50%', '51-75%', '76-90%', '91-100%']),
      helpText: 'Healthy teams have 60-80% quota attainment',
      required: true,
      order: 12,
    },

    // Performance Metrics
    {
      sectionId: 2,
      category: 'Performance Metrics',
      question: 'Do you track sales metrics and KPIs?',
      questionType: 'select',
      options: JSON.stringify(['No tracking', 'Basic tracking (revenue only)', 'Some metrics tracked', 'Comprehensive dashboard', 'Real-time analytics with forecasting']),
      helpText: 'You can\'t improve what you don\'t measure',
      required: true,
      order: 13,
    },
    {
      sectionId: 2,
      category: 'Performance Metrics',
      question: 'Which metrics do you actively track?',
      questionType: 'multiselect',
      options: JSON.stringify(['Pipeline value', 'Win rate', 'Average deal size', 'Sales cycle length', 'Conversion rates by stage', 'Activity metrics (calls, emails, meetings)', 'Quota attainment', 'Forecast accuracy', 'Customer acquisition cost (CAC)', 'None of these']),
      helpText: 'Select all that apply',
      required: true,
      order: 14,
    },
    {
      sectionId: 2,
      category: 'Performance Metrics',
      question: 'How often do you review sales performance?',
      questionType: 'select',
      options: JSON.stringify(['Rarely/never', 'Monthly', 'Bi-weekly', 'Weekly', 'Daily']),
      helpText: 'Frequent reviews enable faster course correction',
      required: true,
      order: 15,
    },
    {
      sectionId: 2,
      category: 'Performance Metrics',
      question: 'What is your current win rate?',
      questionType: 'select',
      options: JSON.stringify(['Don\'t know', 'Less than 10%', '10-20%', '20-30%', '30-40%', '40-50%', 'Over 50%']),
      helpText: 'Win rate indicates sales effectiveness',
      required: true,
      order: 16,
    },

    // Win/Loss Analysis
    {
      sectionId: 2,
      category: 'Win/Loss Analysis',
      question: 'Do you conduct win/loss analysis?',
      questionType: 'select',
      options: JSON.stringify(['No', 'Occasionally', 'For major deals only', 'Systematically for all deals', 'Systematically with third-party interviews']),
      helpText: 'Win/loss analysis reveals blind spots',
      required: true,
      order: 17,
    },
    {
      sectionId: 2,
      category: 'Win/Loss Analysis',
      question: 'What are the top 3 reasons you lose deals?',
      questionType: 'textarea',
      options: null,
      helpText: 'Price, competitor features, timing, etc.',
      required: true,
      order: 18,
    },
    {
      sectionId: 2,
      category: 'Win/Loss Analysis',
      question: 'What are the top 3 reasons you win deals?',
      questionType: 'textarea',
      options: null,
      helpText: 'Features, relationship, ROI, etc.',
      required: true,
      order: 19,
    },

    // Sales Technology
    {
      sectionId: 2,
      category: 'Sales Technology',
      question: 'What CRM do you use?',
      questionType: 'select',
      options: JSON.stringify(['No CRM', 'Spreadsheets', 'Salesforce', 'HubSpot', 'Pipedrive', 'Zoho', 'Microsoft Dynamics', 'Other']),
      helpText: 'CRM is foundational for sales operations',
      required: true,
      order: 20,
    },
    {
      sectionId: 2,
      category: 'Sales Technology',
      question: 'What is your CRM adoption rate?',
      questionType: 'select',
      options: JSON.stringify(['N/A - no CRM', '0-25%', '26-50%', '51-75%', '76-90%', '91-100%']),
      helpText: 'Low adoption = poor data quality',
      required: true,
      order: 21,
    },
    {
      sectionId: 2,
      category: 'Sales Technology',
      question: 'What other sales tools do you use?',
      questionType: 'multiselect',
      options: JSON.stringify(['Sales engagement (Outreach, Salesloft)', 'Intelligence (ZoomInfo, LinkedIn Sales Nav)', 'Conversation intelligence (Gong, Chorus)', 'Proposal/CPQ', 'Email tracking', 'Calendar scheduling', 'Video conferencing', 'None']),
      helpText: 'Select all that apply',
      required: true,
      order: 22,
    },
  ];

  // Sales Enablement Maturity Questions
  const enablementQuestions = [
    // Content & Resources
    {
      sectionId: 3,
      category: 'Content & Resources',
      question: 'Do you have a centralized repository for sales content?',
      questionType: 'select',
      options: JSON.stringify(['No', 'Shared drive (unorganized)', 'Shared drive (organized)', 'Sales enablement platform', 'CRM-integrated content library']),
      helpText: 'Content accessibility impacts sales efficiency',
      required: true,
      order: 1,
    },
    {
      sectionId: 3,
      category: 'Content & Resources',
      question: 'What sales content do you have available?',
      questionType: 'multiselect',
      options: JSON.stringify(['Pitch decks', 'Case studies', 'ROI calculators', 'Product demos', 'Competitive battle cards', 'Objection handling guides', 'Email templates', 'Call scripts', 'Proposal templates', 'None of these']),
      helpText: 'Select all that apply',
      required: true,
      order: 2,
    },
    {
      sectionId: 3,
      category: 'Content & Resources',
      question: 'How often is your sales content updated?',
      questionType: 'select',
      options: JSON.stringify(['Rarely/never', 'Annually', 'Quarterly', 'Monthly', 'As needed (continuous)']),
      helpText: 'Stale content hurts credibility',
      required: true,
      order: 3,
    },
    {
      sectionId: 3,
      category: 'Content & Resources',
      question: 'Do you track which content is most effective?',
      questionType: 'select',
      options: JSON.stringify(['No', 'Anecdotally', 'Basic tracking', 'Comprehensive analytics', 'AI-powered insights']),
      helpText: 'Content analytics reveal what works',
      required: true,
      order: 4,
    },

    // Training & Development
    {
      sectionId: 3,
      category: 'Training & Development',
      question: 'Do you have a formal onboarding program for new sales hires?',
      questionType: 'select',
      options: JSON.stringify(['No formal program', 'Informal shadowing', 'Structured 1-2 week program', 'Comprehensive 30-day program', 'Full 90-day ramp program']),
      helpText: 'Onboarding speed impacts time-to-productivity',
      required: true,
      order: 5,
    },
    {
      sectionId: 3,
      category: 'Training & Development',
      question: 'How long does it take for a new sales hire to become productive?',
      questionType: 'select',
      options: JSON.stringify(['Less than 1 month', '1-2 months', '3-4 months', '5-6 months', '7-9 months', '10-12 months', 'Over 12 months']),
      helpText: 'Time to productivity = time to first deal',
      required: true,
      order: 6,
    },
    {
      sectionId: 3,
      category: 'Training & Development',
      question: 'Do you provide ongoing training for your sales team?',
      questionType: 'select',
      options: JSON.stringify(['No', 'Ad hoc when issues arise', 'Quarterly training sessions', 'Monthly training sessions', 'Continuous learning program']),
      helpText: 'Continuous learning drives improvement',
      required: true,
      order: 7,
    },
    {
      sectionId: 3,
      category: 'Training & Development',
      question: 'What types of training do you provide?',
      questionType: 'multiselect',
      options: JSON.stringify(['Product knowledge', 'Sales methodology', 'Industry/market training', 'Competitive intelligence', 'Soft skills (communication, negotiation)', 'Tool/technology training', 'None']),
      helpText: 'Select all that apply',
      required: true,
      order: 8,
    },
    {
      sectionId: 3,
      category: 'Training & Development',
      question: 'Do you certify sales reps on key competencies?',
      questionType: 'select',
      options: JSON.stringify(['No certification', 'Informal assessment', 'Formal certification for some skills', 'Comprehensive certification program', 'Continuous certification with recertification']),
      helpText: 'Certification ensures minimum competency',
      required: true,
      order: 9,
    },

    // Technology & Tools
    {
      sectionId: 3,
      category: 'Technology & Tools',
      question: 'How would you rate your sales technology stack?',
      questionType: 'rating',
      options: JSON.stringify({ min: 1, max: 10 }),
      helpText: '1 = Lacking critical tools, 10 = Best-in-class stack',
      required: true,
      order: 10,
    },
    {
      sectionId: 3,
      category: 'Technology & Tools',
      question: 'Do your sales tools integrate with each other?',
      questionType: 'select',
      options: JSON.stringify(['No integration', 'Some manual data transfer', 'Basic integrations', 'Most tools integrated', 'Fully integrated tech stack']),
      helpText: 'Integration reduces manual work',
      required: true,
      order: 11,
    },
    {
      sectionId: 3,
      category: 'Technology & Tools',
      question: 'Do you provide training on sales tools?',
      questionType: 'select',
      options: JSON.stringify(['No', 'Self-service resources only', 'Initial training at rollout', 'Ongoing training sessions', 'Comprehensive enablement with certifications']),
      helpText: 'Tool proficiency impacts adoption',
      required: true,
      order: 12,
    },
    {
      sectionId: 3,
      category: 'Technology & Tools',
      question: 'What percentage of your sales team actively uses your sales tools?',
      questionType: 'select',
      options: JSON.stringify(['0-25%', '26-50%', '51-75%', '76-90%', '91-100%']),
      helpText: 'Low adoption = wasted investment',
      required: true,
      order: 13,
    },

    // Coaching & Management
    {
      sectionId: 3,
      category: 'Coaching & Management',
      question: 'Do your sales managers provide regular coaching?',
      questionType: 'select',
      options: JSON.stringify(['No', 'Occasionally', 'Monthly', 'Bi-weekly', 'Weekly', 'Daily']),
      helpText: 'Coaching is the #1 driver of sales performance',
      required: true,
      order: 14,
    },
    {
      sectionId: 3,
      category: 'Coaching & Management',
      question: 'What types of coaching do managers provide?',
      questionType: 'multiselect',
      options: JSON.stringify(['Deal strategy coaching', 'Skill development', 'Call/demo reviews', 'Pipeline reviews', 'Forecast reviews', 'Performance improvement plans', 'None']),
      helpText: 'Select all that apply',
      required: true,
      order: 15,
    },
    {
      sectionId: 3,
      category: 'Coaching & Management',
      question: 'Do you use conversation intelligence tools (Gong, Chorus, etc.)?',
      questionType: 'select',
      options: JSON.stringify(['No', 'Considering', 'Recently adopted', 'Actively using', 'Deeply integrated into coaching']),
      helpText: 'Conversation intelligence enables data-driven coaching',
      required: true,
      order: 16,
    },
    {
      sectionId: 3,
      category: 'Coaching & Management',
      question: 'Have your sales managers been trained on coaching skills?',
      questionType: 'select',
      options: JSON.stringify(['No', 'Informal/self-taught', 'Some training', 'Formal coaching certification', 'Ongoing coaching development']),
      helpText: 'Great reps don\'t automatically make great coaches',
      required: true,
      order: 17,
    },

    // Metrics & Analytics
    {
      sectionId: 3,
      category: 'Metrics & Analytics',
      question: 'Do you measure the impact of your enablement programs?',
      questionType: 'select',
      options: JSON.stringify(['No', 'Anecdotal feedback', 'Basic metrics (completion rates)', 'Performance metrics (quota attainment)', 'Comprehensive ROI analysis']),
      helpText: 'Enablement should be measured like any investment',
      required: true,
      order: 18,
    },
    {
      sectionId: 3,
      category: 'Metrics & Analytics',
      question: 'Which enablement metrics do you track?',
      questionType: 'multiselect',
      options: JSON.stringify(['Training completion rates', 'Time to productivity', 'Content usage', 'Certification rates', 'Quota attainment', 'Win rate improvement', 'Sales cycle reduction', 'None']),
      helpText: 'Select all that apply',
      required: true,
      order: 19,
    },
    {
      sectionId: 3,
      category: 'Metrics & Analytics',
      question: 'Do you have a dedicated sales enablement team or role?',
      questionType: 'select',
      options: JSON.stringify(['No', 'Sales ops handles it', 'Part-time enablement role', 'Dedicated enablement manager', 'Full enablement team']),
      helpText: 'Enablement requires dedicated focus',
      required: true,
      order: 20,
    },

    // Alignment & Strategy
    {
      sectionId: 3,
      category: 'Alignment & Strategy',
      question: 'How aligned are your sales and marketing teams?',
      questionType: 'rating',
      options: JSON.stringify({ min: 1, max: 10 }),
      helpText: '1 = Completely siloed, 10 = Perfectly aligned',
      required: true,
      order: 21,
    },
    {
      sectionId: 3,
      category: 'Alignment & Strategy',
      question: 'Do you have a formal sales playbook?',
      questionType: 'select',
      options: JSON.stringify(['No', 'Informal/tribal knowledge', 'Basic documented playbook', 'Comprehensive playbook', 'Dynamic playbook with continuous updates']),
      helpText: 'Playbooks codify best practices',
      required: true,
      order: 22,
    },
    {
      sectionId: 3,
      category: 'Alignment & Strategy',
      question: 'How would you rate your overall sales enablement maturity?',
      questionType: 'rating',
      options: JSON.stringify({ min: 1, max: 10 }),
      helpText: '1 = Non-existent, 10 = World-class',
      required: true,
      order: 23,
    },
  ];

  // Insert all questions
  const allQuestions = [...icpQuestions, ...methodologyQuestions, ...enablementQuestions];
  
  for (const q of allQuestions) {
    await db.insert(icpAssessmentQuestions).values({
      sectionId: q.sectionId,
      category: q.category,
      question: q.question,
      questionType: q.questionType,
      options: q.options,
      helpText: q.helpText,
      required: q.required,
      order: q.order,
    });
  }

  console.log(`✅ ${allQuestions.length} questions created`);
  console.log('🎉 ICP & Sales Enablement Assessment seeded successfully!');
  
  process.exit(0);
}

seedICPAssessment().catch((error) => {
  console.error('❌ Seeding failed:', error);
  process.exit(1);
});

