CREATE TABLE `platforms` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`platform` varchar(255) NOT NULL,
	`useCase` text,
	`website` varchar(500),
	`costOwner` enum('Client','GTM Planetary','Both') NOT NULL,
	`status` enum('Active','Inactive','Cancelled') NOT NULL DEFAULT 'Active',
	`billingType` enum('Monthly','Yearly','OneTime','Usage','Free Plan','Pay as you go'),
	`licenses` varchar(100),
	`monthlyAmount` int DEFAULT 0,
	`yearlyAmount` int DEFAULT 0,
	`oneTimeAmount` int DEFAULT 0,
	`balanceUsage` int DEFAULT 0,
	`renewalDate` date,
	`renewalDay` int,
	`isMyToolbelt` boolean DEFAULT false,
	`isInternalBusiness` boolean DEFAULT false,
	`isSolutionPartner` boolean DEFAULT false,
	`notesForManus` text,
	`notesForStaff` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `platforms_id` PRIMARY KEY(`id`)
);
